registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views


urlpatterns = patterns('',
    url(r'^$', views.Consultar.as_view(), name='consultar'),
    url(r'^registrar$', views.Registrar.as_view(), name='registrar'),
    url(r'^editar/(?P<pk>\d+)$', views.Editar.as_view(), name='editar'),
    url(r'^borrar/(?P<pk>\d+)$', views.Borrar.as_view(), name='borrar'),
)

registro_vistas_clases/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Persona(models.Model):
    nombre = models.CharField(max_length=200)
    cedula = models.CharField(max_length=8)

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('registro:editar', kwargs={'pk': self.pk})

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from registro.models import Persona
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage


class Consultar(ListView):
    model = Persona


class Registrar(CreateView):
    model = Persona
    fields = ['nombre', 'cedula']
    success_url = reverse_lazy('registro:consultar')


class Editar(UpdateView):
    model = Persona
    fields = ['nombre', 'cedula']
    success_url = reverse_lazy('registro:consultar')


class Borrar(DeleteView):
    model = Persona
    success_url = reverse_lazy('registro:consultar')

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>
      {% block titulo %}Base{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </head>
  <body>
    <!-- navbar class
    ================================================== -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Registro de datos usando clases genéricas de Django</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'registro:consultar' %}">Lista</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- navbar class end -->
    <!-- container class
    ================================================== -->
    <div class="container theme-showcase" role="main">
      <div class="well">
      {% block cuerpo %}
      {% endblock %}
      </div>
    </div>
    <!-- container class end -->
  </body>
</html>

registro/templates/registro/persona_confirm_delete.html
{% extends "registro/base.html" %}
{% block titulo %}Borrar{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  ¿Está seguro que desea borrar a "{{ object }}" ?
  <button class="btn btn-danger" type="submit">BORRAR</button>
</form>
{% endblock %}

registro/templates/registro/persona_form.html
{% extends "registro/base.html" %}
{% block titulo %}Registrar{% endblock %}
{% block cuerpo %}
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success" type="submit">GUARDAR</button>
</form>
{% endblock %}

registro/templates/registro/persona_list.html
{% extends "registro/base.html" %}
{% block titulo %}Lista{% endblock %}
{% block cuerpo %}
<h1>Lista de personas</h1>
<br />
<a href="{% url 'registro:registrar' %}">
  <button class="btn btn-success">NUEVA</button>
</a>
<br />
<br />
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th class="text-center">ID</th>
      <th class="text-center">Nombre</th>
      <th class="text-center">Cédula</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>
  <tbody>
  {% for persona in object_list %}
  <tr>
    <td class="text-center">{{ persona.id }}</td>
    <td class="text-center">{{ persona.nombre }}</td>
    <td class="text-center">{{ persona.cedula }}</td>
    <td class="text-center">
      <a href="{% url 'registro:editar' persona.id %}">
        <button class="btn btn-info">EDITAR</button>
      </a>
      <a href="{% url 'registro:borrar' persona.id %}">
        <button class="btn btn-danger">BORRAR</button>
      </a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}